apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: itzcookiie/chat-app
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: chat-app
  ports:
    - nodePort: 30163
      port: 5000
      targetPort: 5000